# Generated by Django 5.2.5 on 2025-08-31 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('form', models.CharField(choices=[('tablet', 'Tableta'), ('capsule', 'Cápsula'), ('liquid', 'Líquido'), ('injection', 'Inyección'), ('cream', 'Crema'), ('drops', 'Gotas')], default='tablet', max_length=50)),
            ],
            options={
                'db_table': 'Medications',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('patient', 'Paciente'), ('family', 'Familiar'), ('doctor', 'Médico')], default='patient', max_length=20)),
                ('tz', models.CharField(default='America/Bogota', max_length=50)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pattern', models.CharField(max_length=255)),
                ('dose_amount', models.CharField(max_length=50)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('planned_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('taken', 'Tomado'), ('missed', 'Perdido'), ('skipped', 'Saltado')], default='planned', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schedule')),
            ],
            options={
                'db_table': 'Intakes',
            },
        ),
        migrations.CreateModel(
            name='FamilyPatientRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('relationship_type', models.CharField(choices=[('parent', 'Padre/Madre'), ('child', 'Hijo/Hija'), ('spouse', 'Cónyuge'), ('sibling', 'Hermano/Hermana'), ('grandparent', 'Abuelo/Abuela'), ('grandchild', 'Nieto/Nieta'), ('other', 'Otro')], max_length=20)),
                ('can_manage_medications', models.BooleanField(default=False)),
                ('can_view_medical_data', models.BooleanField(default=True)),
                ('emergency_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relations', to='api.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_family_relations', to='api.user')),
            ],
            options={
                'db_table': 'FamilyPatientRelations',
                'unique_together': {('family_member', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_relations', to='api.user')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_doctor_relations', to='api.user')),
            ],
            options={
                'db_table': 'DoctorPatientRelations',
                'unique_together': {('doctor', 'patient')},
            },
        ),
    ]
